services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    restart: unless-stopped

    environment:
      ACCEPT_EULA: ${ACCEPT_EULA}
      SA_PASSWORD: ${SA_PASSWORD}
      MSSQL_PID: ${MSSQL_PID}
      COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}

    ports:
      - "1433:1433"

    volumes:
      - mssql_data:/var/opt/mssql

    networks:
      - my-net

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - my-net

volumes:
  mssql_data:

networks:
  my-net:           # Define the custom network here
    driver: bridge

